//
// script auto-generated by com.quickeye.ui-toolkit-plus ver: 1.5.0
//
// Namespace determined by:
// 1. If exists: AssemblyDefinitionAsset.rootNamespace/AssemblyDefinitionReferenceAsset in uxml directory or parent directory
// 2. If exists: AssemblyDefinitionAsset.name
// 3. If uxml is in assets folder: EditorSettings.projectGenerationRootNamespace
using UnityEngine.UIElements;

namespace SampleAsmDefName
{
    partial class CodeGenExample
    {
        private Label title;
        private VisualElement menu;
        private Button confirmButton;
        private QuickEye.UIToolkit.Tab normalTab;
        private QuickEye.UIToolkit.TabGroup dropTab;
        private UnityEditor.UIElements.Toolbar toolbar;
    
        protected void AssignQueryResults(VisualElement root)
        {
            title = root.Q<Label>("title");
            menu = root.Q<VisualElement>("menu");
            confirmButton = root.Q<Button>("confirm-button");
            normalTab = root.Q<QuickEye.UIToolkit.Tab>("normal-tab");
            dropTab = root.Q<QuickEye.UIToolkit.TabGroup>("drop--tab");
            toolbar = root.Q<UnityEditor.UIElements.Toolbar>("toolbar");
        }
    }
}
