//
// AUTO GENERATED BY TOOL
//
using UnityEngine;
using UnityEngine.UIElements;
#if UNITY_EDITOR
using UnityEditor.UIElements;
#endif

// Namespace determined by:
// 1. If exists: AssemblyDefinitionAsset.rootNamespace/AssemblyDefinitionReferenceAsset in uxml directory or parent directory
// 2. If exists: AssemblyDefinitionAsset.name
// 3. If uxml is in assets folder: EditorSettings.projectGenerationRootNamespace

namespace QuickEye.UIToolkit.Editor
{
    partial class FileLocationPanel
    {
        private VisualElement fieldsContainer;
        private TextField pathField;
        private Button pathButton;
        private QuickEye.UIToolkit.FileNameField nameField;
        private VisualElement buttonContainer;
        private Button cancelButton;
        private Button addButton;
    
        protected void AssignQueryResults(VisualElement root)
        {
            fieldsContainer = root.Q<VisualElement>("fields-container");
            pathField = root.Q<TextField>("path-field");
            pathButton = root.Q<Button>("path-button");
            nameField = root.Q<QuickEye.UIToolkit.FileNameField>("name-field");
            buttonContainer = root.Q<VisualElement>("button-container");
            cancelButton = root.Q<Button>("cancel-button");
            addButton = root.Q<Button>("add-button");
        }
    }
}
